openapi: 3.0.1
info:
  title: Guideline Compliance
  description: >-
    BIAN Service Domain Packaged Business Capability (PCB) | DDD Bounded Context
    Guideline Compliance (expanded with ISO200022)
  version: 12.0.1
servers:
  - url: ' https://virtserver.swaggerhub.com/BIAN-3/GuidelineCompliance/12.0.1'
paths:
  '/GuidelineComplianceAssessment/Evaluate':
      post:
        tags:
          - CR (DDD Aggregate)  - GuidelineComplianceAssessment'
        summary: (DDD Service) EvCR Start a guideline compliance evaluation assessment
        description: (DDD Service) EvCR Start a guideline compliance evaluation assessment
        operationId: GuidelineComplianceAssessment/Evaluate
        requestBody:
          $ref: >-
            #/components/requestBodies/EvaluateGuidelineComplianceAssessmentRequest
        responses:
          '200':
            $ref: >-
              #/components/responses/EvaluateGuidelineComplianceAssessmentResponse
          '400':
            $ref: '#/components/responses/BadRequest'
          '401':
            $ref: '#/components/responses/Unauthorized'
          '403':
            $ref: '#/components/responses/Forbidden'
          '404':
            $ref: '#/components/responses/NotFound'
          '429':
            $ref: '#/components/responses/TooManyRequests'
          '500':
            $ref: '#/components/responses/InternalServerError'
  '/GuidelineComplianceAssessment/{guidelinecomplianceassessmentid}/Update':
      put:
        tags:
          - CR (DDD Aggregate)  - GuidelineComplianceAssessment'
        summary: >-
          (DDD Service) UpCR Update submitted details or content for an on-going
          guideline compliance assessment
        description: >-
          (DDD Service) UpCR Update submitted details or content for an on-going
          guideline compliance assessment
        operationId: GuidelineComplianceAssessment/Update
        parameters:
          - $ref: '#/components/parameters/guidelinecomplianceassessmentid'
        requestBody:
          $ref: >-
            #/components/requestBodies/UpdateGuidelineComplianceAssessmentRequest
        responses:
          '200':
            $ref: '#/components/responses/UpdateGuidelineComplianceAssessmentResponse'
          '400':
            $ref: '#/components/responses/BadRequest'
          '401':
            $ref: '#/components/responses/Unauthorized'
          '403':
            $ref: '#/components/responses/Forbidden'
          '404':
            $ref: '#/components/responses/NotFound'
          '429':
            $ref: '#/components/responses/TooManyRequests'
          '500':
            $ref: '#/components/responses/InternalServerError'
  '/GuidelineComplianceAssessment/{guidelinecomplianceassessmentid}/Retrieve':
      get:
        tags:
          - CR (DDD Aggregate) - GuidelineComplianceAssessment'
        summary: >-
          (DDD Service) ReCR Retrieve details and content from an active
          guideline compliance assessment
        description: >-
          (DDD Service) ReCR Retrieve details and content from an active
          guideline compliance assessment
        operationId: GuidelineComplianceAssessment/Retrieve
        parameters:
          - $ref: '#/components/parameters/guidelinecomplianceassessmentid'
        responses:
          '200':
            $ref: >-
              #/components/responses/RetrieveGuidelineComplianceAssessmentResponse
          '400':
            $ref: '#/components/responses/BadRequest'
          '401':
            $ref: '#/components/responses/Unauthorized'
          '403':
            $ref: '#/components/responses/Forbidden'
          '404':
            $ref: '#/components/responses/NotFound'
          '429':
            $ref: '#/components/responses/TooManyRequests'
          '500':
            $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    EvaluateGuidelineComplianceAssessmentRequest:
        type: object
        properties:
          GuidelineComplianceAssessmentType:
              type: string
              description: '|||'
              format: String
          BusinessUnitReference:
              type: string
              description: '|||'
              format: Object
          ProductandServiceReference:
              type: string
              description: '|||'
              format: Object
          CustomerReference:
              type: string
              description: '|||'
              format: Object
          DocumentReference:
              type: string
              description: '|||'
              format: Object
          GuidelineComplianceAssessmentWorkProducts:
              type: string
              description: '|||'
              format: String
    EvaluateGuidelineComplianceAssessmentResponse:
        type: object
        properties:
          DocumentReference:
              type: string
              description: '|||'
              format: Object
          GuidelineComplianceAssessmentWorkProducts:
              type: string
              description: '|||'
              format: String
          GuidelineComplianceAssessmentResult:
              type: string
              description: '|||'
              format: String
    EvaluateGuidelineComplianceAssessment:
        type: object
        properties:
          GuidelineComplianceAssessmentType:
              type: string
              description: "||\r\n|"
              format: String
          BusinessUnitReference:
              type: string
              description: "||\r\n|"
              format: Object
          ProductandServiceReference:
              type: string
              description: "||\r\n|"
              format: Object
          CustomerReference:
              type: string
              description: "||\r\n|"
              format: Object
          DocumentReference:
              type: string
              description: "||\r\n|"
              format: Object
          GuidelineComplianceAssessmentWorkProducts:
              type: string
              description: "||\r\n|"
              format: String
          GuidelineComplianceAssessmentResult:
              type: string
              description: "||\r\n|"
              format: String
    UpdateGuidelineComplianceAssessmentRequest:
        type: object
        properties:
          GuidelineComplianceAssessmentType:
              type: string
              description: '|||'
              format: String
          BusinessUnitReference:
              type: string
              description: '|||'
              format: Object
          ProductandServiceReference:
              type: string
              description: '|||'
              format: Object
          CustomerReference:
              type: string
              description: '|||'
              format: Object
          DocumentReference:
              type: string
              description: '|||'
              format: Object
          GuidelineComplianceAssessmentWorkProducts:
              type: string
              description: '|||'
              format: String
    UpdateGuidelineComplianceAssessmentResponse:
        type: object
        properties:
          GuidelineComplianceAssessmentType:
              type: string
              description: '|||'
              format: String
          BusinessUnitReference:
              type: string
              description: '|||'
              format: Object
          ProductandServiceReference:
              type: string
              description: '|||'
              format: Object
          CustomerReference:
              type: string
              description: '|||'
              format: Object
          DocumentReference:
              type: string
              description: '|||'
              format: Object
          GuidelineComplianceAssessmentWorkProducts:
              type: string
              description: '|||'
              format: String
    UpdateGuidelineComplianceAssessment:
        type: object
        properties:
          GuidelineComplianceAssessmentType:
              type: string
              description: "||\r\n|"
              format: String
          BusinessUnitReference:
              type: string
              description: "||\r\n|"
              format: Object
          ProductandServiceReference:
              type: string
              description: "||\r\n|"
              format: Object
          CustomerReference:
              type: string
              description: "||\r\n|"
              format: Object
          DocumentReference:
              type: string
              description: "||\r\n|"
              format: Object
          GuidelineComplianceAssessmentWorkProducts:
              type: string
              description: "||\r\n|"
              format: String
          GuidelineComplianceAssessmentResult:
              type: string
              description: "||\r\n|"
              format: String
    RetrieveGuidelineComplianceAssessmentResponse:
        type: object
        properties:
          GuidelineComplianceAssessmentType:
              type: string
              description: '|||'
              format: String
          BusinessUnitReference:
              type: string
              description: '|||'
              format: Object
          ProductandServiceReference:
              type: string
              description: '|||'
              format: Object
          CustomerReference:
              type: string
              description: '|||'
              format: Object
          DocumentReference:
              type: string
              description: '|||'
              format: Object
          GuidelineComplianceAssessmentWorkProducts:
              type: string
              description: '|||'
              format: String
          GuidelineComplianceAssessmentResult:
              type: string
              description: '|||'
              format: String
    RetrieveGuidelineComplianceAssessment:
        type: object
        properties:
          GuidelineComplianceAssessmentType:
              type: string
              description: "||\r\n|"
              format: String
          BusinessUnitReference:
              type: string
              description: "||\r\n|"
              format: Object
          ProductandServiceReference:
              type: string
              description: "||\r\n|"
              format: Object
          CustomerReference:
              type: string
              description: "||\r\n|"
              format: Object
          DocumentReference:
              type: string
              description: "||\r\n|"
              format: Object
          GuidelineComplianceAssessmentWorkProducts:
              type: string
              description: "||\r\n|"
              format: String
          GuidelineComplianceAssessmentResult:
              type: string
              description: "||\r\n|"
              format: String
    HTTPError:
        type: object
        properties:
          status_code:
            type: string
            format: string
          status:
            type: string
            format: string
          message:
            type: string
            format: string
        description: Status Attributes
  responses:
    EvaluateGuidelineComplianceAssessmentResponse:
        description: GuidelineComplianceAssessmentEvaluate
        content:
          'application/json:':
            schema:
              $ref: >-
                #/components/schemas/EvaluateGuidelineComplianceAssessmentResponse
    UpdateGuidelineComplianceAssessmentResponse:
        description: GuidelineComplianceAssessmentUpdate
        content:
          'application/json:':
            schema:
              $ref: '#/components/schemas/UpdateGuidelineComplianceAssessmentResponse'
    RetrieveGuidelineComplianceAssessmentResponse:
        description: GuidelineComplianceAssessmentRetrieve
        content:
          'application/json:':
            schema:
              $ref: >-
                #/components/schemas/RetrieveGuidelineComplianceAssessmentResponse
    BadRequest:
        description: BadRequest
        content:
          'application/json:':
            schema:
              $ref: '#/components/schemas/HTTPError'
    Unauthorized:
        description: Unauthorized
        content:
          'application/json:':
            schema:
              $ref: '#/components/schemas/HTTPError'
    Forbidden:
        description: Forbidden
        content:
          'application/json:':
            schema:
              $ref: '#/components/schemas/HTTPError'
    NotFound:
        description: NotFound
        content:
          'application/json:':
            schema:
              $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
        description: TooManyRequests
        content:
          'application/json:':
            schema:
              $ref: '#/components/schemas/HTTPError'
    InternalServerError:
        description: InternalServerError
        content:
          'application/json:':
            schema:
              $ref: '#/components/schemas/HTTPError'
  parameters:
    guidelinecomplianceassessmentid:
        name: guidelinecomplianceassessmentid
        in: path
        required: true
        style: simple
        schema:
          type: string
  requestBodies:
    EvaluateGuidelineComplianceAssessmentRequest:
        content:
          'application/json:':
            schema:
              $ref: >-
                #/components/schemas/EvaluateGuidelineComplianceAssessmentRequest
        required: true
    UpdateGuidelineComplianceAssessmentRequest:
        content:
          'application/json:':
            schema:
              $ref: '#/components/schemas/UpdateGuidelineComplianceAssessmentRequest'
        required: true
    RetrieveGuidelineComplianceAssessmentRequest:
        content:
          'application/json:':
            schema:
              type: string
        required: true
