name: Semanticore
on:
  push:
    branches:
      - master
jobs:
  semanticore:
    runs-on: ubuntu-latest
    name: Semanticore
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.*"
      - name: Semanticore
        run: go run github.com/rock-hu/technology_radar
        env:
          SEMANTICORE_TOKEN: ${{secrets.GITHUB_TOKEN}}
